// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/screen-time/Dashboard.tsx": () => import("../components/mockups/screen-time/Dashboard.tsx"),
  "./components/mockups/clearspace-modal/Modal.tsx": () => import("../components/mockups/clearspace-modal/Modal.tsx")
};
